// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCupQ6SYYc8V1W00Ficu6H8FIV1cfblupI',
    appId: '1:88952222936:android:0b2d429685a3230e4ed3ad',
    messagingSenderId: '88952222936',
    projectId: 'bicycle-hire---codebreakers',
    storageBucket: 'bicycle-hire---codebreakers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMnrVORDVI6T2JuKijtURdwE-K4NHEggQ',
    appId: '1:88952222936:ios:0371524366724d664ed3ad',
    messagingSenderId: '88952222936',
    projectId: 'bicycle-hire---codebreakers',
    storageBucket: 'bicycle-hire---codebreakers.appspot.com',
    iosClientId:
        '88952222936-m7178qeojeln4o6vvfuit40lv67345jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.bicycleHireApp',
  );
}
